In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("data/processed/target_ready.csv")
df.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,at_risk
0,2024-08-27 11:29:31,37.0,Female,United States,IL,No,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,1
1,2024-08-27 11:29:37,44.0,M,United States,IN,No,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,0
2,2024-08-27 11:29:44,32.0,Male,Canada,CA,No,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,0
3,2024-08-27 11:29:46,31.0,Male,United Kingdom,CA,No,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,1
4,2024-08-27 11:30:22,31.0,Male,United States,TX,No,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,0

In [3]:
df = df[(df['Age'] >= 18) & (df['Age'] <= 65)]
df['Gender'] = df['Gender'].str.lower().str.strip()
df['Gender'] = df['Gender'].replace({
    'male': 'Male', 'm': 'Male', 'man': 'Male',
    'female': 'Female', 'f': 'Female', 'woman': 'Female'
})
categorical_cols = ['Gender', 'Country', 'self_employed', 'family_history']
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df['Age_scaled'] = scaler.fit_transform(df[['Age']])

In [10]:
df.to_csv("data/processed/features_ready.csv", index=False)